### ISSUE TITLE
All checks: Fix entry hyperlink

### ISSUE THREAD

**Issue by kelseylarson** [PovertyAction/high-frequency-checks#106]
For the scto_link variable, clicking on the excel hyperlink sends you to the general survey monitoring page, not the specific survey. However, if you copy and paste the link into your browser, it will successfully take you to the specific survey. Since you need to copy and paste to get the link to go to the right place, it would be better to just display the URL rather than trying to turn it into a hyperlink.

**Comment by boyercb** [comment]
This solution using Mata seems to get around the hyperlink issue 

```
mata:
b = xl()
b.create_book("test.xlsx", "test")
b.put_formula(1,1, `"HYPERLINK("https://www.google.com")"')
b.set_font(1,1, "Calibri", 11, "5 99 193")
b.set_font_underline(1,1, "on")
b.close_book()
end
```

You really don't need the b.set_font() and b.set_font_underline() lines as it will create a clickable hyperlink without them, but for some reason Excel doesn't automatically style the hyperlinks with the traditional blue font and underline. I added them so it would strictly be more obvious to the user that they are indeed clickable.

**Comment by boyercb** [comment]
Also from SurveyCTO:

> Hi Lindsey, Chris,
>
>So okay, we're confident that we now, in 2.41, have sufficient technology to be able to reliably hyperlink from Excel to the Data Explorer, for any given submission. All that's needed is the server name (for the first part of the URL) and the UUID/KEY (for the second part of the URL). (To make Windows Office happy, we have an un-secured landing page that then has a button to login and continue...) Now we'd like to make sure that IPA/JPAL/DIME/etc. people who use the IPA HFC system have hyperlinks into the Data Explorer available where needed.
>
>How do we go about this?
>
>When we were at DIME last week, they said that they just used the IPA code straight from github, and I presume that IPA and other users are much the same. What's the right protocol for working hyperlinks in? Would you want us to try to figure it out, then issue a pull request? Or..? We're happy to help however we can, and mostly would just love to make it easier to investigate HFC warnings in the DE... Please let us know.
>
>Thanks!
>
>Chris

This will involve changing references from this: 
```Stata
*generate scto_link variable
if !missing("`sctodb'") {
	replace scto_link = subinstr(key, ":", "%3A", 1)
	replace scto_link = `"=HYPERLINK("https://`sctodb'.surveycto.com/view/submission.html?uuid="' + scto_link + `"", "View Submission")"'
}
```
To this:

```Stata
*generate scto_link variable
if !missing("`sctodb'") {
	replace scto_link = subinstr(key, ":", "%3A", 1)
	replace scto_link = `"=HYPERLINK("https://`sctodb'.surveycto.com/officelink.html?url=" & SUBSTITUTE(SUBSTITUTE(SUBSTITUTE( SUBSTITUTE(SUBSTITUTE(SUBSTITUTE( SUBSTITUTE(SUBSTITUTE(SUBSTITUTE("https://`sctodb'.surveycto.com/view/submission.html?uuid="' + scto_link + `"", "%", "%25"), " ", "%20"), "?", "%3F"), "&", "%26"), "=", "%3D"), "{", "%7B"), "}", "%7D"), "[", "%5B"), "]", "%5D"), "View Submission")"'
}
```

I will submit a PR with these changes
