### ISSUE TITLE
Fix inputs import for multiple surveys

### ISSUE THREAD

**Issue by rachelauryn** [PovertyAction/high-frequency-checks#135]
On line 17 of master_check when you import the inputs sheet, it breaks if you set up folders for multiple surveys, since the inputs sheet put within subfolders with each survey name and with the survey name appended to it. For example:
ipacheckimport using "../04_checks/01_inputs/hfc_inputs.xlsm"
should be 
ipacheckimport using "../04_checks/01_inputs/1_endline/hfc_inputs_endline.xlsm"
if you have multiple surveys, with the survey you're running the hfc for called "endline"
I'm not sure how to fix this without having users edit the stata code.

**Comment by rsandino** [comment]
I think we do expect someone to change that line if they are not using the default name that we expect, i.e. using multiple surveys or if they just wanted to change the file name.
