### ISSUE TITLE
ipadoheader does not set version

### ISSUE THREAD

**Issue by kbjarkefur** [PovertyAction/high-frequency-checks#155]
No command in Stata can change the version outside the scope of that command. As soon as a command is done Stata automatically resets any changes to version number done inside the command. To see this, run this code in a version later than version 14.0:
```
ipadoheader, version(14.0)
version
```
It is unlikely to have unintended consequences as long as `ipadoheader` is not used in a do-file with randomization where version setting is important in addition to _seed_ and _sort_, but the output of `ipadoheader` claims that version is changed which is not correct.

See the [help file for ieboilstart](https://github.com/worldbank/ietoolkit/blob/master/src/help_files/ieboilstart.sthlp) for a way how the same issue solved in `ieboilstart` which this command was based on. There we solved it by storing the `version 14.0` (or whatever version you used) in a return local and which is used immediately afterward, like this:
```
ieboilstart , versionnumber(14.0)
`r(version)'
version
```

**Comment by khattar24** [comment]
When I run this command, ipadoheader, version(15.0) it shows an error, ipadoheader command unrecognised. What could be possible reasons?

**Comment by iabaako** [comment]
> When I run this command, ipadoheader, version(15.0) it shows an error, ipadoheader command unrecognised. What could be possible reasons?

I'm not sure why you have this problem. My guess is that there are some challenges with your installation of ipacheck. Are you able to run any of the other ipacheck commands?

I will suggest that you re-install ipacheck by running the following command in the Stata command window and try again. 

`net install ipacheck, from("https://raw.githubusercontent.com/PovertyAction/high-frequency-checks/master/ado") replace`

**Comment by iabaako** [comment]
Removed from dms4
