### ISSUE TITLE
Issues with if_condition column in 6. Logic checks

### ISSUE THREAD

**Issue by mayaian93** [PovertyAction/high-frequency-checks#160]
Hello @rsandino @iparesearch, 

I and @Odoulami are still encountering some issues with the hfc 6 (logic checks). After have runthe command _ipacheck update hotfix_, we manage to run the logic checks and we get the output file with the logic section. However, from the output file we can see that there is an issue with how the program is reading the if_condition column. Sometimes the if_condition is not read at all, sometimes it is read well and sometimes the if_condition belonging to another line it is applied.

Is there way you can help us with this issue?

Thanks a lot!

**Comment by rsandino** [comment]
Hi @mayaian93, sorry this keeps continuing! I think I have fixed it now. Can you use `ipacheck update hotfix` again, and see if it is resolved?

**Comment by mayaian93** [comment]
Hi @rsandino,

Thanks a lot, now the logic checks are working perfectly!

We have also another small issue with the back checks. The do file runs and it create the bc_diffs.xlsx output file which apparently is corrupted, so neither I nor @Odoulami managed to open it. We had to changed the extension to xls and it opened as a csv. In addition, I am not sure that the options okrange_min and okrange_max are working, as I see listed also some differences for values that fall within that range!

I would be great if you could help us on this as well!

Thanks a lot for all your support!

**Comment by rsandino** [comment]
@mayaian93, can you send the code so we can troubleshoot?

**Comment by mayaian93** [comment]
Hello @rsandino @Odoulami, 

Here is the code for the backchecks part!

Let me know if you need any other info!

Thanks a lot for your help

`/* ===============================================================
   =================== Analyze Back Check Data ===================
   =============================================================== */

use "Data/backchecks data", clear
destring hhid, replace
save, replace  
   
if ${run_backcheck} {
  bcstats, ///
      surveydata("${sdataset_f}_checked")  ///
      bcdata("${bdataset}")  ///
      id(${id})              ///
      enumerator(${enum})    ///
      enumteam(${enumteam})  ///
      backchecker(${bcer})   ///
      bcteam(${bcerteam})    ///
      t1vars(${type1_17})    ///
      t2vars(${type2_17})    ///
      t3vars(${type3_17})    ///
      ttest(${ttest17})      ///
      keepbc(${keepbc17})    ///
      keepsurvey(${keepsurvey17}) ///
    ///  reliability(${reliability17}) ///
      filename("${bcfile}") ///
      exclude(${bcexclude}) ///
      ${bclower} ${bcupper} ${bcnosymbols} ${bctrim} ///
      ${bcshowall} ${bcshowrate} ${bcfull} ///
      ${bcnolabel} ${bcreplace}
}

`

**Comment by rsandino** [comment]
Hi @mayaian93  and @Odoulami, the okrange option is missing from the template do file. If you add the line `okrange(${okrange17})` as an option, the okrange should work. 

As for the filename corruption, can you send me what you have entered as ${bcfile}?

**Comment by Odoulami** [comment]
Hi @rsandino 
Thanks for your reply. As ${bcfile}, we keep "bc_diffs.xlsx" in the tab 0.setup. We didn’t change anything. 

One random thought I heard from a friend about the file corruption issue is that it often happens when the folder hosting the outputs is encrypted. In our case, we planned to do so but for now, the outputs folder is not encrypted. Then the issue might be elsewhere.

Thanks

**Comment by rsandino** [comment]
@mayaian93 , can you create a log file where you run the part of the master_check do file that runs ipacheckimport, add the code `macro list` after running ipacheckimport, and send me that? There might be an issue with how Stata is reading the directory.

**Comment by mayaian93** [comment]
Hey @rsandino , very sorry for the late reply!

Please find log file attached! Thanks a lot!
[hfc log.log](https://github.com/PovertyAction/high-frequency-checks/files/4614442/hfc.log.log)
