### ISSUE TITLE
Bug when running IPATRACKVERSION

### ISSUE THREAD

**Issue by emawbgit** [PovertyAction/high-frequency-checks#162]
Dear IPA,

I have the following issue when running the IPATRACKVERSION check. This is occurring after 2 months of correct functioning of such command. Any hint on this? Thanks in advance
<img width="960" alt="issue_ipatrackversion" src="https://user-images.githubusercontent.com/65594313/85417837-c12ee380-b578-11ea-950f-ed3ff65e2708.PNG">

**Comment by mfiorina** [comment]
Adding on to this, as a new/other issue seems to have popped up in our use of ipatrackversions. We get the error message "<istmt>:  3499  tab_to_dta() not found
r(3499);"

Which seems to be related to the mata: tab_to_dta() lines in the .ado file (?). Any hopes this could be solved?
