### ISSUE TITLE
Using OR condition in consent check

### ISSUE THREAD

**Issue by khattar24** [PovertyAction/high-frequency-checks#170]
I want to add more than one variable for consent check. Rather than ADD condition, I want to utilize OR condition, that if either of the variable is true, consent should be marked as true.

**Comment by iabaako** [comment]
Hello Khattar, you should generate a new dummy variable and use that for the consent check. For instance, if you have the following:

q1. consent_treatment "Custom text ... Are all your questions answered to your satisfaction?"
q2. consent_control "Custom text  ... Are all your questions answered to your satisfaction?"

You can generate a new variable 

```Stata
gen consent = consent_treatment == 1 | consent_control == 1
```
