### ISSUE TITLE
ipacheck wont work on Stata16

### ISSUE THREAD

**Issue by umairali90** [PovertyAction/high-frequency-checks#171]
This is the error code I receive, can this be made backwards compatible? 
this is version 16.1 of Stata; it cannot run version 17.0 programs
     You can purchase the latest version of Stata by visiting https://www.stata.com.

**Comment by iabaako** [comment]
> This is the error code I receive, can this be made backwards compatible? this is version 16.1 of Stata; it cannot run version 17.0 programs You can purchase the latest version of Stata by visiting https://www.stata.com.

Hello, 

Yes, unfortunately, the new version of the DMS (v4.0) makes use of Stata "data frames" which is only available on **Stata 17 or later**. Please refer to the [FAQ page](https://github.com/PovertyAction/high-frequency-checks/wiki/FAQs) for this information as well as information on how to install and use 
older versions of the **DMS (v3.0)** which is available on **Stata version 14.2 or later.** 

If you are an IPA employee, kindly email researchsupport@poverty-action.org to learn how to get access to Stata 17.
