### ISSUE TITLE
Variable not found for ipacheckenumdb

### ISSUE THREAD

**Issue by elkimpov** [PovertyAction/high-frequency-checks#173]
I am having trouble running the exercise example because the ipacheckenumdb command runs into an error that says the variables in hfc_inputs.xlsm do not exist. I checked before and after trunning the command, and the variables do exist in the dataset. Is there a way to resolve this error?

**Comment by iabaako** [comment]
This issue was resolved a while back. Please update ipacheck and try again. You can re-open this if the issue still persists.
