### ISSUE TITLE
variable a_bcer_id not found

### ISSUE THREAD

**Issue by sally-lago** [PovertyAction/high-frequency-checks#176]
I keep on getting the error variable a_bcer_id not found des*5te a3ready def5n5n5ng 5t 5n the global.do file

**Comment by iabaako** [comment]
Thanks for bringing this issue to our attention. Kindly send a traced log-file (in SMCL format) to researchsupport@poverty-action.org to help us diagnose and resolve this issue?

Also, kindly run the command "ipacheck version" and send a screenshot of the output as well. 

Kind Regards
