### ISSUE TITLE
Ado file ipacheckoutliers error combine variable

### ISSUE THREAD

**Issue by ifurlani** [PovertyAction/high-frequency-checks#178]
Hello! 

I encountered an error when running the HFCs because the variable combine was undefined. As others might stumble upon the same issue, I raised it here.  
The error was appearing because Stata should keep some variables in the command/ado file, among which the variable 'combine' cannot be found.

_My solution:_
In the ado file for the command ipacheckoutliers, I commented out line 247: _rename combine combine_vars_  

_Alternative proposed solution:_ 
Modify until the end of the ado file combine with combine_vars.

**Comment by iabaako** [comment]
Hello @ifurlani, 

Thanks for reaching out. 

What version of `ipacheckoutliers` are you using? It is likely to be a problem that was fixed already and you can fix this by updating your DMS. You can update your DMS by running the command `net install ipacheck, all replace from("https://raw.githubusercontent.com/PovertyAction/high-frequency-checks/master") force` and the `ipacheck update`. You can check your version with the command `ipacheck version`. The latest version of `ipacheckoutliers` is `4.0.3   06jan2023`. 

Please let me know if you still face this challenge after updating your DMS. 

Kind Regards

**Comment by ifurlani** [comment]
Hello,

I do have the last version of everything.
As you suggested, I re-run the lines to update everything (therefore going back to the version without my solution), and the error appears again.
[cid:d97964d0-0eff-4298-9181-af8eac8e4c23]
If I re-insert my solution in the ado file (taking out/ commenting the rename command away), it works again.

Best,
Irene

________________________________

**Comment by iabaako** [comment]
Hello Irene, 

Thanks again for the additional info. Unfortunately, I am unable to replicate this error in several test and tweaks and I haven't had this report from any other user. It is important to us to track and fix these kinds of issues so it will be helpful if we could get on a call so you can help diagnose this issue. Kindly reach out to me on skype (iabaako) so we can schedule a call. 

Hope to hear from you soon. 

Kind Regards
Ishmail

**Comment by iabaako** [comment]
Hello Irene, 

Thanks for helping with this. ipacheckoutliers has been updated to fix this issue.
