### ISSUE TITLE
ipachecksurveydb - variable jvar contains missing values

### ISSUE THREAD

**Issue by HilaireBtr** [PovertyAction/high-frequency-checks#179]
Hi there, 

I'm working on a RCT, and was glad to find this whole IPA HFC package. I'm just a bit puzzled when running the _ipachecksurveydb_ command, since I get a mysterious error message: 

variable jvar contains missing values

Does anyone have a clue of what jvar is ?

Thanks a lot!

PS : exactly same issue with _ipacheckenumdb_

**Comment by HilaireBtr** [comment]
Hi @iabaako , 

Thanks for your quick answer. 

- I indeed have the latest version of ipachecksurveydb. 
- My Stata version is 17.0
- Here is the log: [Git hub issue ipacheck.log](https://github.com/PovertyAction/high-frequency-checks/files/13561332/Git.hub.issue.ipacheck.log)


Thanks for your help. 
Cheers, 
Hilaire

![ipacheck version](https://github.com/PovertyAction/high-frequency-checks/assets/66431642/472e7e94-fef8-45bd-a0a4-e295f82b097a)

**Comment by iabaako** [comment]
Hello @HilaireBtr, 

Thanks for sending the files. Unfortunately the Log file you sent doesn't have the trace set on. Could you send another log-file in SMCL format with a `set trace on` (just before the ipachecksurveydb command). 

Kind Regards

**Comment by HilaireBtr** [comment]
Hey,

Thanks again for your support.
Here is the attached file SMCL, as it is impossible to accach this kind of
file in the Git issue.

Many thanks,
Hilaire

**Comment by HilaireBtr** [comment]
Here is the detailled log file in txt format if you cannot receive my email. 
[Uploading Git hub issue ipacheck.log…]()

**Comment by iabaako** [comment]
I believe this issue was resolved a while back. If you are still experiencing this issue, please re-open.
