### ISSUE TITLE
Allow wild cards in checks 1, 3, 6, 8, 10, and 11

### ISSUE THREAD

**Issue by boyercb** [PovertyAction/high-frequency-checks#30]
## Background

In Stata users can abbreviate variable lists using the wild cards `*` and `-`. For instance, 

``` Stata
ds rep*
```

returns all variables which start with the charaters `rep`, like

``` Stata
rep1 replacement repairs repetition rep34
```

Alternatively, using the `-` wildcard

``` Stata
ds mpg-weight
```

 returns all variables from mpg through weight in the order of the data set, e.g.

``` Stata
mpg rep78 headroom trunk weight
```

Several HFC check commands allow the use of wildcards in the `hfc_inputs.xlsx` file so that users can abbreviate variable lists for the sake of expediency.
## The Problem

In checks like the constraints check where additional items are supposed to apply to each row-item in the `hfc_inputs.xlsx` file, wild cards can break the command logic leading to strange bugs.

**Comment by catonbrewster** [comment]
As discussed, this is an issue with many of the checks. I think it should be high priority to fix this and make it so users can use wildcards in all of the checks. 

Surveys rely on repeat groups too much to not make the inputs handle them automatically (the alternative is them having to update the inputs with every change to how many iterations of a repeat group that we have).

**Comment by boyercb** [comment]
Each of the commands for the checks in question loop over the primary variable list, e.g.
```Stata
foreach var in varlist {
    * run check on each variable...
}
```

To allow wild cards and/or multiple variables per row, I think the solution is to unabbreviate (using `unab` macro function) and add an inner loop that runs if there is more than one variable in the row. This inner loop would run the check code for each variables. However, any of the attributes defined in subsequent columns would have to be grouped and moved just before the inner loop to ensure they remain constant across the row, e.g.

```Stata
foreach var in varlist {
    * define constants for this row...

    unab innerlist : `var' 
    foreach inner in innerlist {
        * run check on each variable...
    }
}
```
