### ISSUE TITLE
#2: bug for id variable that follows a previous id where there were no duplicates found

### ISSUE THREAD

**Issue by boyercb** [PovertyAction/high-frequency-checks#31]
## The Problem

I get an error message when I check for duplicates on more than one variable. The error is `r(110)` and it seems to come from the second `duplicates tag` command’s `generate( )` option. The second time it repeats the loop, the code is bringing up `dup1` instead of a new variable name (presumably `dup2`)

See the output with trace on:

_first variable_

```
  - duplicates tag `var', gen(`dup1')
  = duplicates tag supplierid1, gen(__000000)
```

_second variable_

```
- duplicates tag `var', gen(`dup1')
 = duplicates tag q8_phone_1, gen(__000000)
```

The latter fails with the following error message.

```
ERROR:  generate() must specify new variable
```

**Comment by kelseylarson** [comment]
Looks like this issue is fixed: can we close it?
