### ISSUE TITLE
Program: use survey form to create output that suggests vars to include in HFCs

### ISSUE THREAD

**Issue by catonbrewster** [PovertyAction/high-frequency-checks#34]
# The Problem 
The HFC inputs file is time consuming to fill in, especially if there is a survey with thousands of lines. Want to brainstorm ways to make it easier and faster to set up

# Possible Solution
Create a program that would help make suggestions of variables to include in HFCs. 

# Status
Currently have very crude do file that imports the form and just browses based on the check I want to generate a list for - would be good to refine this code (and build upon it) to produce a program that would generate output of minimum variables to consider when filling in the inputs excel sheet. The more automated we can make this, the better. Output could be "suggested inputs" sheet? With hints on each tab of potential caveats and other types of variables to manually consider. 

Example: 
```stata
//specify
gen cvars = ""
gen pvars = ""

//get list of specify other vars
levelsof name, local(vars)
foreach var of local vars {
    qui count if name == "`var'_oth"
    if `r(N)' > 0 {
        replace pvars = "`var'" if name == "`var'"
        replace cvars = "`var'_oth" if pvars == "`var'"
        }
    }
gsort- cvars
order cvars pvars 
br cvars pvars
```

**Comment by boyercb** [comment]
This has morphed into `fillhfcs`

**Comment by rsandino** [comment]
@iabaako
