### ISSUE TITLE
#0: change to no longer have to switch from replace to modify after first run

### ISSUE THREAD

**Issue by catonbrewster** [PovertyAction/high-frequency-checks#42]
The do file template is now set up such that when this first check is run it has ", replace" at the end and a comment says to switch to ", modify" after the first time running HFCs. 

Would be great to automate this within the program because caused some issues for me when I forgot to switch this.

**Comment by boyercb** [comment]
@catonbrewster 

If we switch the summary sheet this one is no longer necessary.
