### ISSUE TITLE
#8: the do file does not have space to enter hard min/max but then program requires it

### ISSUE THREAD

**Issue by catonbrewster** [PovertyAction/high-frequency-checks#47]
Currently, when you download to do file that goes with the template, this check is not set up to automatically incorporate the hard min/max columns from the inputs sheet. _However_, the code in the program requires a hard min and max, so we need to make those optional.

**Comment by boyercb** [comment]
This is resolved in the current [master_check](https://github.com/PovertyAction/high-frequency-checks/blob/master/master_check.do) do-file.
