### ISSUE TITLE
HFC11: add a column in the inputs sheet of values to ignore

### ISSUE THREAD

**Issue by catonbrewster** [PovertyAction/high-frequency-checks#53]
Have this list of values and then update the program to ignore any values specified. 

People sometimes include codes that they don't recode to extended missing values (e.g. in an integer question they will assign meaning to "-333", "-444", etc) so don't want these skewing outlier calculations. 

Caton already made this update in a v2 so just need to incorporate code.

**Comment by kelseylarson** [comment]
Caton and I were talking, and this should be an easy one for me to knock off.
