### ISSUE TITLE
Change programs to work with Stata's native -touch- program

### ISSUE THREAD

**Issue by boyercb** [PovertyAction/high-frequency-checks#60]
Previously, I had defined my own version of the UNIX console's `touch` command to create blank temp files.

```Stata
program touch
	syntax [anything], [var(varlist)] [replace] 

	* remove quotes from filename, if present
	local file = `"`=subinstr(`"`anything'"', `"""', "", .)'"'

	* test fatal conditions
	cap assert "`file'" != "" 
	if _rc {
		di as err "must specify valid filename."
		error 100
	}

	preserve 

	if "`var'" != "" {
		keep `var'
		drop if _n > 0
	}
	else {
		drop _all
		g var = 1
		drop var
	}
	* save 
	save "`file'", emptyok `replace'

	restore

end
```

But apparently Stata 13 and 14 have a built-in version of `touch`. We should use the built-in version; it's more flexible and may solve some of our tempfile issues.

**Comment by kbjarkefur** [comment]
_(I hope you do not mind that I am commenting on a closed issue. I am happy to move my comment to the merge or open a new issue if you prefer.)_

Are these commands only meant to be running on UNIX machines? The ado-files do not run on Windows computers after the merge in 96f0a28. 

```
HFC 1 => Checking that all interviews are complete...
unrecognized command: touch
r(199);
```
