### ISSUE TITLE
formula() is not a valid option for adding SCTO link in Stata 13 

### ISSUE THREAD

**Issue by boyercb** [PovertyAction/high-frequency-checks#83]
After some testing on my own, it appears that the `formula()` option used to output the formatted hyperlink in commit #70.  Problem code pasted below:

```Stata
    forval x = 1 / `r(N)' {
        loc row = `x' + 1
        loc formula = scto_link[`x']
        loc putlist `"`putlist' `col'`row' = formula(`"`formula'"')"'
     }
     putexcel `putlist'
```

**Comment by dancjensen** [comment]
It appears the "formula" option is new to Stata 14.1, and extended formatting abilities to Stata 14.2.

See [here](http://www.stata.com/new-in-stata/excel-cell-formatting/).

Had the same problem and find it really irritating that there isn't a user-written extension to get around this, as Stata upgrades are expensive! You can insert it as text, something like:
`putexcel " `putlist' " `
but Excel won't actually calculate the formula upon opening the program until you do something, like modifying the cell, to tell it that you've inserted a formula, not text.

I haven't explored further workarounds--there might be a way to get Excel to reference whatever you insert and treat it as a formula, but honestly I haven't had the time to try, so I've resorted to just making my calculations in Stata and saving them as values in Excel.
